version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

    depends_on:
      - db

  back:
    image: back
    container_name: python-fastapi-slim
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn asgi:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
     - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./back:/back

  redis:
    image: redis
    restart: on-failure
    command: "redis-server --requirepass ${REDIS_PASSWORD:-secret}"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  rq_worker:
    image: back
    command: rq worker -c worker_settings
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres_data:
    driver: local
  
  redis_data:
    driver: local
