name: Make update
on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update and re-run system
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "Create ssh connection with server"
          eval `ssh-agent -k` > /dev/null
          eval `ssh-agent -s` > /dev/null

          echo "start agent"
          echo "$SSH_PRIVATE_KEY" > secret_key
          chmod 600 secret_key
          ssh-add secret_key

          SSH_CMD="ssh -T -A -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER"
          $SSH_CMD << EOF
            cd test-accelerator-project/
            git reset --hard
            git pull
            docker compose buil --no-cache
            docker compose up -d
            docker compose exec back alembic uprade head
            docker compose exec back pytest
          EOF
